#!/usr/bin/env python3
"""HR01 gate reassessment (11) and remaining evidence (12); adds the HR01 outcome column to the queue baseline (02).

Run from the repository root:  python3 -I GEM_V3.0_RC2_HR01_Human_Review_Queue_Closure/16_scripts/hr01_build_gate_registers.py
No gate is closed by this script or by HR01. Every row states the five levels: review completed / finding resolved / evidence obtained /
acceptance condition satisfied / gate may close.
"""
import csv
from pathlib import Path

PKG = Path("GEM_V3.0_RC2_HR01_Human_Review_Queue_Closure")
G_H = ["Gate", "Current state (Register + OD01)", "New evidence from HR01", "Governing acceptance requirement (Register)", "1 Review completed", "2 Finding resolved",
       "3 Evidence obtained", "4 Acceptance condition satisfied", "5 Gate may close", "Can close?", "Reason", "Remaining dependency"]
LEG = "Document not in the repository and not reviewed; the Register's owner (Legal / IP Counsel) has not accepted it. A statement that a document exists is not evidence."
GATES = [
    ["VAL-03", "Not started", "Owner states a hard-copy document exists (type, issuer, date not stated); not supplied or reviewed", "Target-market clearance or documented legal advice", "Queue 4 evidence review: complete", "No", "Pointer only", "No", "No", "NO", LEG, "Scan or photograph into the confidential brand archive; Legal / IP Counsel reviews and accepts"],
    ["Y01", "Evidence Required", "As VAL-03", "Trademark availability/registration legally reviewed", "Complete", "No", "Pointer only", "No", "No", "NO", LEG, "As VAL-03"],
    ["VAL-04", "Not started", "Owner states a document exists outside the repository (type not stated); not supplied or reviewed", "Ownership or assignment/licence evidence retained with the brand archive", "Complete", "No", "Pointer only", "No", "No", "NO", "Document not retained in the archive and not reviewed; provenance statement ('received from the project owner') is not ownership evidence.", "Supply and retain the document; Brand Owner / Legal accepts"],
    ["Y02", "Evidence Required", "As VAL-04", "Logo artwork ownership documented", "Complete", "No", "Pointer only", "No", "No", "NO", "As VAL-04", "As VAL-04"],
    ["VAL-05", "In progress", "OFL 1.1 text and copyright lines for the three Regular builds located and read; font manifest status WORKING BUILD", "Licences support intended print, web, app, office and distribution uses; exact builds tested where needed", "Complete", "No", "Partial (licence text for Regular builds)", "No", "No", "NO", "Exact final builds not frozen/accepted; deployment-use verification not done; no licence documents for any other build; external verification not used.", "Freeze builds; licence documents for any further build; counsel/Design Custodian confirm uses"],
    ["Y03", "Evidence Required", "As VAL-05", "Licences adequate for print/web/app use", "Complete", "No", "Partial", "No", "No", "NO", "As VAL-05", "As VAL-05"],
    ["VAL-06", "Not started", "Owner states the Part D concept images were generated by the owner using ChatGPT image generation; terms record not supplied", "Every approved production image has rights/source/usage metadata", "Complete", "No", "Provenance statement only", "No", "No", "NO", "No rights register; generation-tool terms not supplied or verified; Part D imagery stays concept/reference.", "Build the rights register; record tool terms; counsel review"],
    ["Y04", "Evidence Required", "As VAL-06", "Image/model/property rights documented", "Complete", "No", "Provenance statement only", "No", "No", "NO", "As VAL-06", "As VAL-06"],
    ["VAL-07", "Not started", "Mashal's human linguistic review of all 44 items (+4 extras): 31 approved as is, 13 revised; approved edits natively validated; VoiceOver SR-06, SR-07, SR-10 PASS (macOS)", "Continuous RTL layouts, shaping, numerals, mixed-language content and screen-reader order pass native review", "Yes (Queue 1)", "Yes for reviewed strings", "Partial", "No", "No", "NO",
     "Review is not gate acceptance. Continuous production RTL layouts with real multi-page content, Windows Word / Word Online and cross-reader (SR-12) are not tested; the corrected candidates remain unapproved implementation candidates.", "Production RTL layouts with real content; Windows/Word Online; promotion of candidates; Brand Owner decision (AC10)"],
    ["VAL-08", "In progress", "Content queue complete (30 titles, 31 pictures, 89 shapes); native checkers: no missing alt text on A/B/C/D, no missing title on A/C; VoiceOver macOS PASS on 11 tests; Part A slide 33 owner-confirmed specimen", "WCAG 2.2 AA target tested in real digital/document outputs; issues resolved or formally excepted", "Yes (Queues 2 and 3)", "Partly", "Partial (macOS VoiceOver only)", "No", "No", "NO",
     "No conformance claim is supported: text-over-picture contrast (113 runs) unmeasured, reading-order advisory flags unchanged, Windows AT and PDF tests deferred, formal exceptions not recorded, independent Accessibility QA holder unnamed.", "SR-12; D8 PDF; contrast; formal exceptions; independent QA"],
    ["VAL-15", "Not started", "Candidates open natively with no repair; Word/PowerPoint checkers run; no PDF regenerated", "Final editable deck opens, saves, reopens and exports without repair, clipping, substitution or accessibility regression", "n/a", "n/a", "Partial (open/render only)", "No", "No", "NO", "No final deliverables exist; save/reopen/export, tagged PDF and Acrobat checks not performed (SR-11 deferred to D8).", "Final deliverables; D8"],
    ["VAL-21", "Not started", "112 automated consistency assertions PASS on the HR01 candidates (identical to the AX01 baseline)", "Documents share version, asset IDs, terminology and approval status without conflict", "n/a", "n/a", "Automated assertions only", "No", "No", "NO", "Text/metadata assertions are not a formal cross-document sign-off.", "Formal sign-off after final documents exist"],
    ["AC10", "Evidence Required", "Mashal's linguistic review; Arabic tagline stays English (M10 not requested); Arabic inside Part D images not approved", "Arabic system approved or formally deferred", "Yes (Queue 1)", "n/a", "Partial", "No", "No", "NO", "AC10 is a Brand Owner decision with localization evidence; no approval or formal deferral was exercised.", "Brand Owner decision after the VAL-07 conditions"],
    ["AC19", "OPEN / HOLDER CONDITION INCOMPLETE (Register: Approved with modification)", "None (1 of 12 canonical roles named, OD-G09)", "Actual named role holders assigned before release", "n/a", "n/a", "No", "No", "No", "NO", "11 of 12 canonical holders (including the Brand Owner) unnamed; OD-G10 is a working assignment, not a canonical role.", "Name the remaining holders"],
    ["AC20", "OPEN / FINAL RELEASE AUTHORIZATION PENDING", "None", "Brand Owner authorizes release after critical evidence gates", "n/a", "n/a", "No", "No", "No", "NO", "Upstream gates above are open; GitHub publication is not release authorization.", "All upstream evidence; named Brand Owner"],
    ["D8", "OPEN", "None (SR-11 deferred to D8)", "Approved native PDF route and tests", "n/a", "n/a", "No", "No", "No", "NO", "No HR01 PDF; Acrobat/tagged-PDF validation not run.", "D8 route and tests"],
]
with open(PKG / "11_HR01_Gate_Impact_Matrix.csv", "w", encoding="utf-8", newline="") as fh:
    w = csv.writer(fh, lineterminator="\n")
    w.writerow(G_H)
    w.writerows(GATES)

R_H = ["Remaining evidence", "Gate(s) blocked", "Owner", "Next action", "Why still open"]
REM = [
    ["Legal / IP Counsel review of GEM trademark position", "VAL-03; Y01", "Legal / IP Counsel (unnamed)", "Retain the hard-copy document in the confidential archive; counsel reviews", "No reviewed legal advice or clearance"],
    ["Logo artwork ownership / assignment document", "VAL-04; Y02", "Brand Owner + Legal / IP Counsel", "Supply and retain the document; Brand Owner / Legal accepts", "Provenance statement is not ownership evidence"],
    ["Frozen font builds and licence documents for any build beyond the Regular files", "VAL-05; Y03; VAL-19", "Design Custodian + Legal / IP Counsel", "Freeze builds; confirm deployment uses; licence documents for further builds", "Only OFL text for three Regular builds is in the repository"],
    ["Image rights register incl. generation-tool terms", "VAL-06; Y04", "Art Direction + Legal / IP Counsel", "Record source/usage per image; supply tool terms; counsel review", "Part D imagery is concept/reference only"],
    ["Continuous production RTL layouts with real multi-page content", "VAL-07", "Arabic / Localization Lead", "Test real letters and documents", "Templates are single-page samples"],
    ["Windows Word / Word Online and cross-reader (SR-12) validation", "VAL-07; VAL-08", "Accessibility QA (unnamed)", "Test on Windows with NVDA/JAWS", "No Windows environment"],
    ["Native PDF route, Acrobat and tagged-PDF validation (SR-11)", "D8; VAL-15; VAL-08", "Presentation / Document QA", "Define route and run tests", "No PDF regenerated in HR01"],
    ["Contrast of text over pictures (113 runs) and formal accessibility exceptions", "VAL-08", "Accessibility QA (unnamed)", "Manual contrast checks; record exceptions", "Not measurable statically"],
    ["Independent Accessibility QA holder", "VAL-08", "Brand Owner", "Name the holder", "Content owner cannot also be the independent verifier"],
    ["Brand Owner decision on the Arabic system (approve or formally defer)", "AC10", "Brand Owner", "Decide after the VAL-07 conditions", "No decision exercised"],
    ["Brand approval of any Arabic tagline (M10), if wanted", "AC10", "Brand Owner", "Only if a translation is requested", "Tagline stays English"],
    ["Linguistic review of Arabic text embedded in Part D images", "VAL-07; VAL-06", "Arabic / Localization Lead", "Review when production artwork exists", "Concept images; wording not approved"],
    ["Promotion of HR01 candidates into authoritative folders", "VAL-15; VAL-21", "Brand Owner (separate authorization)", "Separate authorized change", "Candidates are unapproved implementation candidates"],
    ["Eleven unnamed canonical role holders", "AC19; AC20", "Brand Owner", "Name holders", "Register requires names before release"],
    ["Final cross-document release consistency sign-off", "VAL-21", "Brand Governance / Design Custodian", "Perform on final documents", "Only automated assertions exist"],
    ["Final Brand Owner release authorization", "AC20", "Brand Owner", "After upstream evidence is closed or formally dispositioned", "OPEN"],
]
with open(PKG / "12_HR01_Remaining_Evidence.csv", "w", encoding="utf-8", newline="") as fh:
    w = csv.writer(fh, lineterminator="\n")
    w.writerow(R_H)
    w.writerows(REM)

# queue baseline: add the HR01 outcome column
rows = list(csv.reader(open(PKG / "02_HR01_Queue_Baseline.csv", encoding="utf-8")))
if rows[0][-1] != "HR01 outcome":
    out = {
        "Q1": "REVIEW COMPLETE (44/44 dispositioned + 4 extra items): 31 approve as is, 13 approve Claude recommendation, 0 deferred",
        "Q2": "CONTENT REVIEW COMPLETE (144/144 dispositioned + 2 extra items); native alt-text and title rules clear on the HR01 candidates",
        "Q3": "MANUAL ASSISTIVE-TECH REVIEW COMPLETE FOR DEFINED macOS VOICEOVER SCOPE: 11 PASS (reviewer observed), SR-11 DEFERRED (D8), SR-12 DEFERRED (Windows-native unavailable)",
        "Q4": "EVIDENCE REVIEW COMPLETE (8/8 gates dispositioned): no gate closeable; counsel / licence / rights evidence required",
    }
    rows[0].append("HR01 outcome")
    for r in rows[1:]:
        r.append(out[r[0]])
    with open(PKG / "02_HR01_Queue_Baseline.csv", "w", encoding="utf-8", newline="") as fh:
        csv.writer(fh, lineterminator="\n").writerows(rows)
print("gates", len(GATES), "remaining", len(REM))
