from build_letterheads import *
A='GEM_V3_RC2/04_release/GEM Brand Guidelines V3.0 — Part A — RC2.pptx'
B='PartB_RC2/05_release/GEM Digital Design System V3.0 — Part B — RC2.pptx'
C='GEM_V3_RC2/04_release/GEM Production Standards V3.0 — Part C — RC2.pptx'
REG='GEM_V3_RC2/00_originals/GEM_V3_Final_Brand_Approval_Register_Prefilled.xlsx'
d=Document();s=d.sections[0];s.page_width=Mm(210);s.page_height=Mm(297);s.top_margin=Mm(23);s.bottom_margin=Mm(24);s.left_margin=s.right_margin=Mm(23);s.footer_distance=Mm(12)
for name in ['Normal','Title','Heading 1','Heading 2']:
 st=d.styles[name];st.font.name='Inter' if name=='Normal' else 'Jost';st.font.color.rgb=RGBColor.from_string(INK);st.font.size=Pt(9.5 if name=='Normal' else 17 if name=='Title' else 12)

for x in list(d.styles.element.xpath('.//w:pBdr')):x.getparent().remove(x)
p=s.footer.paragraphs[0];run(p,'GEM™ · LETTERHEAD SET v1.0    ',size=7);field(p,'PAGE');run(p,' / ',size=7);field(p,'NUMPAGES')
p=s.footer.add_paragraph();run(p,'WORKING APPLICATION / PENDING VALIDATION',size=6.5)
def title(text):para(d,text,font='Jost',size=22,style='Title',after=12)
def h(t):para(d,t,font='Jost',size=12,bold=True,style='Heading 1',before=9,after=4,keep=True)
def t(v):para(d,v,size=9.5,after=7)
def source(v):para(d,'Source: '+v,size=7.2,after=9)
title('GEM Letterhead Specification')
t('GEM™ Branded Letterhead Set v1.0\nWORKING APPLICATION / PENDING VALIDATION\nControlled RC2 application for business correspondence. Dimensions and document styles below are proposed application settings, not new approved brand standards.')
h('Page and writing area')
t('A4 portrait 210 × 297 mm. Body margins: 25 mm left/right, 30 mm top, 37 mm bottom; Executive top 36 mm. General writing width: 160 mm. Latin running-body measure: 130 mm (30 mm end indent), bringing representative lines within the 45–75-character target. Arabic uses the full 160 mm RTL writing width; native optical review remains pending. First-page header pushes initial content to approximately 50–56 mm; Minimal approximately 40 mm. Continuation content starts at 30 mm. Subject and body starts vary with recipient and subject length; never fix them to a text box.')
t('Header distance: 18 mm. Footer distance: 12 mm. Footer occupies approximately 264–286 mm from the top. The 37 mm body bottom margin keeps flowing text above this area. These are office-safe application allowances; supplier trim, bleed and mechanical safe-zone values remain [REQUIRES SUPPLIER].')
source(A+' · 67; '+C+' · 20, 44')
h('Logo and clearspace')
t('Use supplied gem-horizontal-ink.svg at 32 mm frame width; Executive 36 mm. Minimal uses gem-horizontal-black.svg at 32 mm. Never edit paths, mirror, stretch or recolour. DOCX carries exact SVG with supplied 2048 px PNG fallback. Both print and digital PDFs retain vector paths from the supplied SVG; no image XObjects are present in the export.')
t('u = G-ring radius. Official horizontal viewBox width 479.8633 units; u = 77.8847655 units. At 32 mm, 1u = 5.19 mm and preferred 2u = 10.39 mm. At 36 mm, preferred 2u = 11.69 mm. The tagline is separated by 12 mm; surrounding page space is greater than 2u. No secondary spark or symbol is added. Digital lockup minimum 120 px; print minimum is not validated here.')
source('GEM_Brand_Assets_v1.0/README.md; 04_official_kit/logo/metrics.json; '+REG+' · H10–H14')
h('Colour and grayscale')
t('Approved brand palette: INK #12171D, BEIGE #BCACA7, BLACK #020202, WHITE #FFFFFF. Text uses Ink; Beige is a 0.5 pt footer rule only. Minimal rule is Black. No Beige text on White. Meaning and status are written explicitly. No background ink flood; no bleed artwork.')
source(REG+' · J01–J04; '+B+' · 7, 8; qa/PartB_RC2_Accessibility_QA_Report.md')
d.add_page_break();title('Type and language')
h('English and office typography')
t('Body: Inter Regular 10.5 pt / 16.8 pt exact leading (1.6×), 6 pt paragraph space after. Subject: real Heading 1, Jost Regular 12 pt / 19.2 pt, zero tracking. Metadata: Inter 8.5 pt. Signatory: Inter Regular 10.5 pt. Footer: Inter 7.5 pt; working-status line 6.5 pt. Approved tagline is optional, Jost 10.5 pt / 15 pt with 0.18em tracking (Word quantized to 1.90 pt), matching the Part B 14/20 px tagline token. Neither secondary line nor a new permanent lockup is introduced.')
source(REG+' · B03, B04, B08, L01–L06, L09; '+B+' · 9–12')
h('Arabic typography and direction')
t('Noto Sans Arabic Regular 11.5 pt / 20.125 pt exact leading (1.75×); subject Regular 12 pt / 21 pt. Zero tracking; no italics. Paragraph-level bidi with logical start alignment produces genuine right-to-left flow. The page section and artwork are not mirrored. Arabic placeholders use guillemets; they are working layout text, not approved corporate or legal wording.')
t('Date and reference labels are Arabic runs; their replaceable Latin identifiers use Inter, explicit LTR runs and Latin digits. Phones, URLs, emails, reference codes and Latin system IDs remain LTR. Guest-facing Arabic-Indic digits are conditional by context; correspondence dates remain replaceable. Gregorian default; Hijri use [REQUIRES OWNER]. No real date or technical numbering convention is invented.')
source(REG+' · M01, M02, M05–M08, M11, M12, DS06; '+B+' · 12, 13, 21; qa/PartB_RC2_RTL_Localization_QA_Report.md')
h('Bilingual correspondence')
t('Arabic recipient block first and right aligned; English equivalent follows, left aligned. Arabic subject first; English subject follows. Arabic body then English body in a single sequential reading order, each in its specified running-body measure. One signature block follows both versions with Arabic placeholders first and the English name/title fields after. For longer letters, complete the Arabic section before its English equivalent and preserve equivalent information. Contact placeholders are one LTR footer line shared by both languages.')
t('S07 explicitly governs Saudi/GCC wayfinding in the register. Part B 12 expands the Arabic-leading mechanics for approved contexts. Applying Arabic-first sequential blocks to correspondence is a PROPOSED APPLICATION / REQUIRES OWNER, not a claim that S07 approves this stationery layout. Arabic release remains PENDING VALIDATION; all working Arabic copy remains PENDING LOCALIZATION APPROVAL.')
source(REG+' · S07, M01; '+A+' · 38, 65; '+B+' · 12, 13; '+C+' · 41')
d.add_page_break();title('Use and production control')
h('First and continuation pages')
t('Use a First Page DOCX as the working document for a complete letter. Its different-first-page header/footer setting automatically switches to the quiet GEM™ and reference identifier on later pages. PAGE and NUMPAGES fields are live. The separate Continuation DOCX is a companion for an existing continued letter; it is not an alternative first page. Replace header/footer contact fields and the repeated reference identifier manually in both header variants.')
t('Keep the closing, 16 mm English or 12 mm Arabic signature reserve, and name/title block together. Allow paragraph flow to repaginate. Long recipients and subjects may push a letter to the next page; do not reduce body size or remove clearspace to force one page. No geometry lies behind text. Executive uses 36 mm logo and more top allowance; Minimal uses the supplied Black logo and one Black rule without tagline.')
h('Office and accessible PDF workflow')
t('Replace all sample content and placeholders before sending. Subject uses a real heading; paragraphs have en-GB/ar-SA run tags. Logo has meaningful alt text; footer rule is a paragraph border, not an unlabeled image. No layout tables or contact icons are used. Embedded full font instances are supplied for office portability, but confirm fonts and line breaks on the recipient platform. Export tagged PDF, preserve selectable text, set primary language and check reading order after export. Tagged structure alone is not an accessibility pass.')
h('Contact and references')
t('No verified company address, phone, email, URL, CR/VAT requirement or correspondence-reference convention was found in the current authoritative set. Use [ADDRESS], [CITY], [COUNTRY], [POSTAL CODE], [T], [E], [W] and [REFERENCE NUMBER]. CR/VAT omitted. Do not replace these with guessed information. A future numbering convention is PROPOSED / REQUIRES OWNER.')
h('Print handoff remains pending')
t('GEM_Letterhead_Print.pdf is an A4 vector-logo print candidate. It is not authorized commercial production artwork. Pantone, CMYK conversion, paper stock/GSM, printer profile, PDF/X standard, output intent, ΔE, finishing and trim/bleed tolerances: [PENDING PREPRESS STANDARD] / [REQUIRES SUPPLIER]. Colour and physical output: [PENDING PHYSICAL PROOF]. Part C 5 release sequence applies before production; do not send with open preflight checks.')
t('Owner: Design Custodian for application review; Arabic / Localization Lead for native language QA; Accessibility QA for AT testing; Legal / IP for trademark, ownership and font approval; Procurement / Supplier QA for prepress and physical proof; Brand Owner for release authorization. No gate is closed by this package.')
source(C+' · 5, 19–21, 44; '+REG+' · VAL-02–05, VAL-07, VAL-08, VAL-15, VAL-19, AC07, AC10, AC17, AC20')
p=R/'03_specs/GEM_Letterhead_Specification.docx';d.core_properties.title='GEM Letterhead Specification';d.core_properties.language='en-GB';configure_edit_styles(d,False);d.save(p);embed_fonts(p)
