"""ODI01-R1 pre-flight: records git state, source/candidate paths and SHA-256 values. Read-only.
Usage: r1_preflight.py <worktree_root> <odi01_full_tree> <out_md>"""
import sys,os,glob,hashlib,subprocess,zipfile
root,odi,out=[os.path.abspath(a) for a in sys.argv[1:4]]
sha=lambda p:hashlib.sha256(open(p,'rb').read()).hexdigest()
def git(*a,cwd=root): return subprocess.run(['git','-C',cwd]+list(a),capture_output=True,text=True).stdout.strip()
primary=git('worktree','list','--porcelain').split('\n')[0].replace('worktree ','')
L=['# 02 Preflight — ODI01-R1','',
 'Read-only checks completed **before any edit** to a candidate file. Generated by `17_scripts/r1_preflight.py`.','',
 '## 1. Execution context','',
 '| Item | Value |','|---|---|',
 f'| Active worktree path | `{root}` |',
 f'| Branch | `{git("branch","--show-current")}` |',
 f'| HEAD | `{git("rev-parse","HEAD")}` |',
 f'| origin/main | `{git("rev-parse","origin/main")}` |',
 f'| Primary checkout | `{primary}` |',
 f'| Primary local main | `{git("rev-parse","main")}` |',
 f'| Working tree state (before the R1 folder was created) | `{git("status","--porcelain","--",".",":(exclude)GEM_V3.0_RC2_Owner_Decision_Implementation_Candidate_ODI01_R1") or "clean"}` (only the new R1 folder is untracked) |',
 f'| Is isolated worktree | {git("rev-parse","--git-dir")!=git("rev-parse","--git-common-dir")} (git-dir differs from common dir) |',
 f'| Remotes | origin={git("remote","get-url","origin")}; letterhead-fork={git("remote","get-url","letterhead-fork")} |','',
 '**Correction (review closure):** no command run for ODI01-R1 wrote to the primary checkout. However, the primary's local `main` was fast-forwarded from `334744c` to `4ea0d11` at 2026-10-09 01:10:05 +0300, and its working tree was updated to match at the same second, by a process this Git evidence cannot identify (`18_qa_evidence/main_ref_movement_investigation.md`). Its untracked entries (`.DS_Store` files, `GEM_Letterhead_Set_v1.0/`) pre-date the session and were not touched. The primary local `main` value recorded in the table above is the value at preflight generation time and is the post-movement value `4ea0d11`.','',
 '```',git('worktree','list'),'```','','```',git('log','--oneline','--decorate','-10'),'```','',
 '## 2. History lineage','',
 'AFC01 `5dbd017`, AFC02 `f346133` and ODI01 `6fbd951` are **not objects in this repository** (`git cat-file -t` fails for all three; no branch contains them). They exist only as delivered packages in `~/Downloads`. ODI01 is therefore carried as an **external, hash-verified input**, not as git history. R1 is based on `HEAD` = `4ea0d11` = `origin/main`. Nothing was rebased, merged or pulled.','',
 '## 3. ODI01 package (external input)','','| File | SHA-256 |','|---|---|']
dl=os.path.expanduser('~/Downloads')
for n in ('ODI01_1_documents_evidence_scripts.zip','ODI01_2_candidate_decks_A_B_C.zip','ODI01_3_D3A_carried_forward_decks.zip'):
    L.append(f'| `~/Downloads/{n}` | `{sha(dl+"/"+n)}` |')
chk=subprocess.run(['shasum','-a','256','-c','SHA256SUMS.txt'],cwd=odi,capture_output=True,text=True)
bad=[l for l in chk.stdout.splitlines() if not l.endswith(': OK')]
L+=['',f'Reassembled ODI01 tree (3 zips + loose Part D files) verified against its own `SHA256SUMS.txt`: **{len(chk.stdout.splitlines())} entries, {len(bad)} mismatches**. Duplicate Downloads copies (`_1`, `_2`) are byte-identical to the unsuffixed files.','',
 '## 4. Original (authoritative) sources — repository paths','','| Doc | Path | SHA-256 |','|---|---|---|']
ORIG={'Part A PPTX':'GEM_V3_RC2/04_release/GEM Brand Guidelines V3.0 — Part A — RC2.pptx','Part B PPTX':'PartB_RC2/05_release/GEM Digital Design System V3.0 — Part B — RC2.pptx','Part C PPTX':'GEM_V3_RC2/04_release/GEM Production Standards V3.0 — Part C — RC2.pptx','Part D PPTX':glob.glob(root+'/Amenities_Portfolio_PartD_RC2/04_release/*.pptx')[0][len(root)+1:],
 'Part B PDF':'PartB_RC2/05_release/GEM Digital Design System V3.0 — Part B — RC2.pdf','Part A review PDF':'GEM_V3_RC2/04_release/GEM Brand Guidelines V3.0 — Part A — RC2 (review export).pdf','Part C review PDF':'GEM_V3_RC2/04_release/GEM Production Standards V3.0 — Part C — RC2 (review export).pdf',
 'Register':'GEM_V3_RC2/00_originals/GEM_V3_Final_Brand_Approval_Register_Prefilled.xlsx','Tokens JSON':'PartB_RC2/05_release/tokens/gem-tokens.v3.0-rc2.json','Tokens CSS':'PartB_RC2/05_release/tokens/gem-tokens.v3.0-rc2.css'}
for k,v in ORIG.items(): L.append(f'| {k} | `{v}` | `{sha(root+"/"+v)}` |')
L+=['','Tracked in git at `HEAD` and unmodified in the working tree (`git diff --quiet HEAD -- <path>` is checked in cross-document QA item 20).','',
 '## 5. ODI01 candidate files (R1 starting point)','','| Doc | ODI01 candidate (file name) | SHA-256 | XML parts differing from original |','|---|---|---|---|']
CD=odi+'/20_candidate_documents/deck_candidates/'
for k,o in (('A','Part A PPTX'),('B','Part B PPTX'),('C','Part C PPTX'),('D','Part D PPTX')):
    c=[p for p in glob.glob(CD+'*.pptx') if f'Part {k} ' in p][0]
    zo=zipfile.ZipFile(root+'/'+ORIG[o]);zc=zipfile.ZipFile(c)
    d=[x for x in zo.namelist() if zo.read(x)!=zc.read(x)]
    L.append(f'| Part {k} | `{os.path.basename(c)}` | `{sha(c)}` | {", ".join(d)} |')
for p in sorted(glob.glob(CD+'*.pdf')): L.append(f'| PDF | `{os.path.basename(p)}` | `{sha(p)}` | LibreOffice 24.2 export |')
for p in ('20_candidate_documents/tokens/gem-tokens.v3.0-rc2.ODI01-candidate.json','20_candidate_documents/tokens/gem-tokens.v3.0-rc2.ODI01-candidate.css'): L.append(f'| Tokens | `{p}` | `{sha(odi+"/"+p)}` | — |')
L+=['','## 6. QA scripts located (ODI01 `19_scripts/`)','','Validation-ID checker = item 15 of `cross_document_qa.py`; 112-assertion suite = `consistency_check_odi01.py`; also `token_status_implementation.py`, `partd_claim_audit.py`, `font_claim_file_matrix.py`/`font_matrix_odi01.py`, `generate_manifest.py`, `verify_manifest.py`, `verify_checksums.py`, `render_reports.py`, `audit_tokens.py`. Font audit report: ODI01 `07_Font_Claim_File_Matrix.csv`, `07_Font_500_Reference_Classification.csv`, `07_Font_400_Restriction_Implementation.md`.','',
 '## 7. Font binaries','','See `07_Font_Claim_File_Matrix.csv` (generated by `17_scripts/r1_font_matrix.py`). Summary: static weight-400 Jost, Inter and Noto Sans Arabic present in the repo; **no 500-weight file exists anywhere**; therefore the stop condition ("newly accepted 500 files have appeared") is **not** triggered.','',
 '## 8. Owner decisions in force (locked, not reopened)','','D1 register = owner-adopted working baseline (no row rewrite) · D4 26 downward token normalizations accepted · D5 400 only, no faux bold, 500 = pending accepted font file · D6 Part D wording corrections accepted · D7 repository visibility NO CHANGE (legal/IP pending) · D8 Arabic/bilingual PDF internal-working only, external blocked; VAL-07, VAL-08, VAL-15 open · AC20 OPEN · D3 UNRESOLVED.','',
 '## 9. Scope of R1','','1. Fix the validation-ID checker so explanatory text about the intentionally unallocated ID number no longer fails, while real active use of that number still fails (with regression tests).','2. Finish D5: remove explicit bold flags on brand-font text and make every remaining 500 reference truthfully "future / pending", with no current-implementation dependency on an unavailable weight.','','Out of scope: letterheads, the 30-slide accessibility queue, D3, D7, tokens other than description wording for 500 intent, any release language.','']
open(out,'w',encoding='utf-8').write('\n'.join(L))
